language: cpp
sudo: required
dist: bionic
compiler:
- gcc
os:
- linux
python: 2.7
bash: 4
cmake: 3.4.3
before_install:
- sudo apt-get install -y libllvm8 llvm-8 llvm-8-dev llvm-8-runtime lld-8 g++-8 ninja-build
- g++-8 --version
- llvm-config-8 --version
- cmake --version
- ninja --version
- python --version
- gcov --version
script:
# Regular tests
- mkdir build && cd build
- cmake -G Ninja -DLLVM_DIR=/usr/lib/llvm-8/lib/cmake/llvm -DCMAKE_CXX_COMPILER=g++-8 ..
- ninja
- ninja test

# ASan
- cd .. && mkdir build-asan && cd build-asan
- cmake -G Ninja -DLLVM_DIR=/usr/lib/llvm-8/lib/cmake/llvm -DCMAKE_CXX_COMPILER=g++-8 -DSANITIZER=ADDRESS ..
- ninja
- ninja test

# TSan
- cd .. && mkdir build-tsan && cd build-tsan
- cmake -G Ninja -DLLVM_DIR=/usr/lib/llvm-8/lib/cmake/llvm -DCMAKE_CXX_COMPILER=g++-8 -DSANITIZER=THREAD ..
- ninja
- ninja test

# UBan
- cd .. && mkdir build-ubsan && cd build-ubsan
- cmake -G Ninja -DLLVM_DIR=/usr/lib/llvm-8/lib/cmake/llvm -DCMAKE_CXX_COMPILER=g++-8 -DSANITIZER=UNDEFINED ..
- ninja
- ninja test

# Code Coverage
- cd .. && mkdir build-coverage && cd build-coverage
- cmake -G Ninja -DLLVM_DIR=/usr/lib/llvm-8/lib/cmake/llvm -DCMAKE_CXX_COMPILER=g++-8 -DCODE_COVERAGE=ON ..
- ninja
- ninja test

after_success:
# Create lcov report
- cd .. && cd build-coverage

# Based off some other issues I found
# (https://github.com/linux-test-project/lcov/issues/38), gcc 8 does not seem
# to work well with whatever version of lcov comes with travis by default. We
# will instead opt for getting a prebuilt that works and using that.
#- wget http://downloads.sourceforge.net/ltp/lcov-1.11.tar.gz
#- tar xvfz lcov-1.11.tar.gz
#- make -C lcov-1.11
- git clone https://github.com/linux-test-project/lcov.git
- cd lcov
- DESTDIR=out make install
- cd ..

- lcov/out/usr/local/bin/cov --capture --directory . --output-file coverage.info
- lcov/out/usr/local/bin/cov -e coverage.info --output-file coverage.info '*qwip-lang/src/*'
- lcov/out/usr/local/bin/cov --list coverage.info # debug info

# Uploading report to CodeCov
- bash <(curl -s https://codecov.io/bash) -f coverage.info || echo "Codecov did not collect coverage reports"
